name: build

on:
  workflow_call:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v4
        
      - name: build debug
        run: |
          ./gradlew assembleDebug
