name: Distribution test version apk

on:
  workflow_call:
    secrets:
      CREDENTIAL_FILE_CONTENT:
        required: true
      FIREBASE_APP_ID:
        required: true

jobs:
  distribution:
    runs-on: ubuntu-latest
    steps:
      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk
          debug: true
