name: Distribution test version apk

on:
  workflow_call:

jobs:
  distribution:
    runs-on: ubuntu-latest
    steps:
      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.PROJECT_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIALS }}
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk
        