name: Distribution test version apk

on:
  workflow_call:
    secrets:
      FIREBASE_CREDENTIALS:
        required: true
      FIREBASE_APP_ID:
        required: true

jobs:
  distribution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Debug secret FIREBASE_CREDENTIALS
        run: |
          echo $SECRET
        env:
          SECRET: ${{ secrets.FIREBASE_CREDENTIALS }}

      - name: Debug secret FIREBASE_APP_ID
        run: |
          echo $SECRET
        env:
          SECRET: ${{ secrets.FIREBASE_APP_ID }}

      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{ secrets.FIREBASE_APP_ID }}
          serviceCredentialsFileContent: ${{ secrets.FIREBASE_CREDENTIALS }}
          groups: testers
          file: app/build/outputs/apk/debug/app-debug.apk
          debug: true
        