name: Main github action

on: 
  push:
    branches: [anhnvd]


jobs:
  setup_java:
    runs-on: ubuntu-latest

    steps:
      - name: checkout 
        uses: actions/checkout@v4

      - name: setup java
        uses: anhnvdgotrack/CICDTestApplictation/.github/workflows/setup/setup_java.yaml