name: Main github action

on: 
  push:
    branches: [anhnvd]

jobs:
  setup_java:
    runs-on: ubuntu-latest

    steps:

      - name: setup java
        uses: ./.github/workflows/setup/setup_java.yaml

      - name: checkout 
        uses: action/checkout@v4
        