name: Main github action

on: 
  push:
    branches: [CNTT-3713_CI_CD_Demo] # anhnvd,

jobs:
  check_out:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@v4

  setup_java:
    needs: [check_out]
    uses: ./.github/workflows/setup_java.yaml

  connect_and_build:
    needs: [setup_java]
    uses: ./.github/workflows/connect_and_build.yaml
    with:
      USERNAME: ${{ vars.USERNAME }}
      HOST: ${{ vars.HOST }}
    secrets: inherit

  # build_test:
  #   needs: [setup_java]
  #   uses: ./.github/workflows/build_test_apk.yaml
  
  # distribution:
  #   needs: [build_test]
  #   uses: ./.github/workflows/distribution_test_apk.yaml
  #   secrets: inherit
